### ISSUE TITLE
Locale on Ubuntu 20.04 is not yet completly translated

### ISSUE THREAD

**Issue by LAfricain** [CristianHenzel/ClipIt#156]
Please update the debian package of clipit. THe current version is 1.4.5 and it's not yet completly localised even if the current po file are 100% translated.

**Comment by afelinczak** [comment]
It will be easier for me if you specify language and example not translated string. I can take a look into build process.

**Comment by LAfricain** [comment]
It's for the french. I downlaod the po file from the source, compile it for French and all the strings are now translated. Maybe you have to update the debian package.

**Comment by afelinczak** [comment]
Seems that issue is related with a problem with meson build script.
When compiled from sources using autotools it works well.
Will investigate.

**Comment by afelinczak** [comment]
Hello @LAfricain 
Thanks again for pointing the issue - seems meson build scripts was an issue here.
While still working on this, uploaded packages to github rebuilt using autotools.
Tested Polish language and it looks good. Please validate and close issue if it works.

Cheers,
Arek

**Comment by LAfricain** [comment]
Hi,
When I try to compile it I have this issue:
```
./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
./configure: eval: line 2518: syntax error near unexpected token `('
./configure: eval: line 2518: `${SHELL} /home/cyrille/Téléchargements/ClipIt-master(1)/ClipIt-master/missing --is-lightweight'
```
I use Ubuntu 20.04

**Comment by afelinczak** [comment]
Hey, never saw issue like that and Im on 20.04 as well.
My best guess is it doesn't like brackets in folder name. Try to remove (1) it may help.

**Comment by LAfricain** [comment]
Correct, I renamed the folder and configure pass, now it's make which doesn't work well:
```
make
make  all-recursive
make[1] : on entre dans le répertoire « /home/cyrille/ClipIt-master »
Making all in data
make[2] : on entre dans le répertoire « /home/cyrille/ClipIt-master/data »
LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po clipit-startup.desktop.in clipit-startup.desktop
Generating and caching the translation database
Merging translations into clipit-startup.desktop.
LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po clipit.desktop.in clipit.desktop
Found cached translation database
Merging translations into clipit.desktop.
make[2] : on quitte le répertoire « /home/cyrille/ClipIt-master/data »
Making all in doc
make[2] : on entre dans le répertoire « /home/cyrille/ClipIt-master/doc »
make[2]: rien à faire pour « all ».
make[2] : on quitte le répertoire « /home/cyrille/ClipIt-master/doc »
Making all in src
make[2] : on entre dans le répertoire « /home/cyrille/ClipIt-master/src »
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16   -Wall -g -DCLIPITLOCALEDIR=\""/usr/local/share/locale"\" -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
In file included from /usr/include/gtk-2.0/gtk/gtkobject.h:37,
                 from /usr/include/gtk-2.0/gtk/gtkwidget.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtktypeutils.h:236:1: warning: ‘GTypeDebugFlags’ is deprecated [-Wdeprecated-declarations]
  236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);
      | ^~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from main.c:31:
/usr/include/glib-2.0/gobject/gtype.h:679:1: note: declared here
  679 | {
      | ^
In file included from /usr/include/gtk-2.0/gtk/gtktoolitem.h:31,
                 from /usr/include/gtk-2.0/gtk/gtktoolbutton.h:30,
                 from /usr/include/gtk-2.0/gtk/gtkmenutoolbutton.h:30,
                 from /usr/include/gtk-2.0/gtk/gtk.h:126,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtktooltips.h:73:3: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   73 |   GTimeVal last_popdown;
      |   ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from main.c:29:
/usr/include/glib-2.0/glib/gtypes.h:547:8: note: declared here
  547 | struct _GTimeVal
      |        ^~~~~~~~~
main.c: In function ‘item_check’:
main.c:211:7: error: unknown type name ‘GdkSeat’; did you mean ‘GdkSpan’?
  211 |       GdkSeat *seat = gdk_display_get_default_seat(display);
      |       ^~~~~~~
      |       GdkSpan
main.c:211:23: warning: implicit declaration of function ‘gdk_display_get_default_seat’; did you mean ‘gdk_display_get_default_screen’? [-Wimplicit-function-declaration]
  211 |       GdkSeat *seat = gdk_display_get_default_seat(display);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       gdk_display_get_default_screen
main.c:211:23: warning: initialization of ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
main.c:213:7: warning: implicit declaration of function ‘gdk_window_get_device_position’; did you mean ‘gdk_window_get_position’? [-Wimplicit-function-declaration]
  213 |       gdk_window_get_device_position(window, gdk_seat_get_pointer(seat), NULL,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       gdk_window_get_position
main.c:213:46: warning: implicit declaration of function ‘gdk_seat_get_pointer’; did you mean ‘gdk_display_get_pointer’? [-Wimplicit-function-declaration]
  213 |       gdk_window_get_device_position(window, gdk_seat_get_pointer(seat), NULL,
      |                                              ^~~~~~~~~~~~~~~~~~~~
      |                                              gdk_display_get_pointer
main.c: In function ‘show_about_dialog’:
main.c:388:25: warning: implicit declaration of function ‘gtk_widget_render_icon_pixbuf’; did you mean ‘gtk_widget_render_icon’? [-Wimplicit-function-declaration]
  388 |                         gtk_widget_render_icon_pixbuf(about_dialog, GTK_STOCK_ABOUT, GTK_ICON_SIZE_MENU));
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         gtk_widget_render_icon
main.c:388:25: warning: passing argument 2 of ‘gtk_window_set_icon’ makes pointer from integer without a cast [-Wint-conversion]
  388 |                         gtk_widget_render_icon_pixbuf(about_dialog, GTK_STOCK_ABOUT, GTK_ICON_SIZE_MENU));
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         int
In file included from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtkwindow.h:286:65: note: expected ‘GdkPixbuf *’ {aka ‘struct _GdkPixbuf *’} but argument is of type ‘int’
  286 |                                                     GdkPixbuf  *icon);
      |                                                     ~~~~~~~~~~~~^~~~
main.c: In function ‘show_actions_menu’:
main.c:510:12: warning: variable ‘fread_return’ set but not used [-Wunused-but-set-variable]
  510 |     size_t fread_return;
      |            ^~~~~~~~~~~~
main.c: In function ‘underline_match’:
main.c:619:29: warning: passing argument 1 of ‘gtk_label_set_attributes’ from incompatible pointer type [-Wincompatible-pointer-types]
  619 |   gtk_label_set_attributes (gtk_label, attr_list);
      |                             ^~~~~~~~~
      |                             |
      |                             GtkWidget * {aka struct _GtkWidget *}
In file included from /usr/include/gtk-2.0/gtk/gtkaccellabel.h:38,
                 from /usr/include/gtk-2.0/gtk/gtk.h:35,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtklabel.h:115:67: note: expected ‘GtkLabel *’ {aka ‘struct _GtkLabel *’} but argument is of type ‘GtkWidget *’ {aka ‘struct _GtkWidget *’}
  115 | void                  gtk_label_set_attributes    (GtkLabel      *label,
      |                                                    ~~~~~~~~~~~~~~~^~~~~
main.c: In function ‘selected_by_input’:
main.c:642:47: warning: passing argument 1 of ‘gtk_container_get_children’ from incompatible pointer type [-Wincompatible-pointer-types]
  642 |   GList* element = gtk_container_get_children(menu);
      |                                               ^~~~
      |                                               |
      |                                               GtkMenuShell * {aka struct _GtkMenuShell *}
In file included from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtkcontainer.h:133:10: note: expected ‘GtkContainer *’ {aka ‘struct _GtkContainer *’} but argument is of type ‘GtkMenuShell *’ {aka ‘struct _GtkMenuShell *’}
  133 | GList*   gtk_container_get_children     (GtkContainer       *container);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
main.c:661:32: warning: passing argument 1 of ‘gtk_widget_set_sensitive’ from incompatible pointer type [-Wincompatible-pointer-types]
  661 |       gtk_widget_set_sensitive(menu_item, true);
      |                                ^~~~~~~~~
      |                                |
      |                                GtkMenuItem * {aka struct _GtkMenuItem *}
In file included from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtkwidget.h:964:72: note: expected ‘GtkWidget *’ {aka ‘struct _GtkWidget *’} but argument is of type ‘GtkMenuItem *’ {aka ‘struct _GtkMenuItem *’}
  964 | void                  gtk_widget_set_sensitive          (GtkWidget    *widget,
      |                                                          ~~~~~~~~~~~~~~^~~~~~
main.c:663:32: warning: passing argument 1 of ‘gtk_widget_set_sensitive’ from incompatible pointer type [-Wincompatible-pointer-types]
  663 |       gtk_widget_set_sensitive(menu_item, false);
      |                                ^~~~~~~~~
      |                                |
      |                                GtkMenuItem * {aka struct _GtkMenuItem *}
In file included from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtkwidget.h:964:72: note: expected ‘GtkWidget *’ {aka ‘struct _GtkWidget *’} but argument is of type ‘GtkMenuItem *’ {aka ‘struct _GtkMenuItem *’}
  964 | void                  gtk_widget_set_sensitive          (GtkWidget    *widget,
      |                                                          ~~~~~~~~~~~~~~^~~~~~
main.c:671:35: warning: passing argument 2 of ‘gtk_menu_shell_select_item’ from incompatible pointer type [-Wincompatible-pointer-types]
  671 |  gtk_menu_shell_select_item(menu, first_match);
      |                                   ^~~~~~~~~~~
      |                                   |
      |                                   GtkMenuItem * {aka struct _GtkMenuItem *}
In file included from /usr/include/gtk-2.0/gtk/gtkmenu.h:36,
                 from /usr/include/gtk-2.0/gtk/gtklabel.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkaccellabel.h:38,
                 from /usr/include/gtk-2.0/gtk/gtk.h:35,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtkmenushell.h:110:20: note: expected ‘GtkWidget *’ {aka ‘struct _GtkWidget *’} but argument is of type ‘GtkMenuItem *’ {aka ‘struct _GtkMenuItem *’}
  110 |      GtkWidget    *menu_item);
      |      ~~~~~~~~~~~~~~^~~~~~~~~
main.c: In function ‘selected_by_digit’:
main.c:723:21: warning: passing argument 1 of ‘gtk_widget_destroy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  723 |  gtk_widget_destroy(history_menu);
      |                     ^~~~~~~~~~~~
In file included from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from main.c:31:
/usr/include/gtk-2.0/gtk/gtkwidget.h:837:50: note: expected ‘GtkWidget *’ {aka ‘struct _GtkWidget *’} but argument is of type ‘const GtkWidget *’ {aka ‘const struct _GtkWidget *’}
  837 | void    gtk_widget_destroy    (GtkWidget        *widget);
      |                                ~~~~~~~~~~~~~~~~~~^~~~~~
main.c: In function ‘main’:
main.c:1085:2: warning: implicit declaration of function ‘umask’ [-Wimplicit-function-declaration]
 1085 |  umask(0077);
      |  ^~~~~
main.c:1141:2: warning: implicit declaration of function ‘init_history_timeout_timer’ [-Wimplicit-function-declaration]
 1141 |  init_history_timeout_timer();
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:448 : main.o] Erreur 1
make[2] : on quitte le répertoire « /home/cyrille/ClipIt-master/src »
make[1]: *** [Makefile:440 : all-recursive] Erreur 1
make[1] : on quitte le répertoire « /home/cyrille/ClipIt-master »
make: *** [Makefile:381 : all] Erreur 2
```

**Comment by afelinczak** [comment]
Not sure, but try to build with gtk 3.0.

**Comment by LAfricain** [comment]
> try to build with gtk 3.0

Ok how to do this?

**Comment by afelinczak** [comment]
./configure --with-gtk3

**Comment by didubu-fr** [comment]
Hi, Same problem with the Ubuntu package. The one from your ppa is ok, thanks.
